version: "3.9"
services:
  web:
    container_name: rust-debian
    build: .
    ports:
      - "8080:8080"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      actix_web: ${actix_web}
      DATABASE_URL: ${DATABASE_URL}
